# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

pool:
  vmImage: ubuntu-latest

variables:
  - template: parameters.yml

steps:

  - task: SonarCloudSetup
    inputs:
      SonarCloud: 'sonarConnection'
      organization: 'app-org-scanner'
      scannerMode: 'Other'
      extraProperties:
        sonar.projectKey=${{ variables.sonarprojectKey }}

  - task: MavenBuild
    inputs:
      mavenPomFile: 'pom.xml'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: ${{ variables.jdkversion }}
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: true
      sqMavenPluginVersionChoice: 'latest'
      goals: 'package'

  - task: PublishTestResults
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/TEST-*.xml'
  - task: SonarCloudPublish
    inputs:
      pollingTimeoutSec: '300'

  - task: PublishArtifacts
    inputs:
      targetPath: '$(Pipeline.Workspace)'
      artifact: ${{ variables.artifactname }}
      publishLocation: 'pipeline'

  - task: DockerBuildAndAcrPush
    inputs:
      containerRegistry: ${{ variables.acrname }}
      repository: ${{ variables.acrrepo }}
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'

