name:  Publish Docker image through commands
 
on: [push]
 
jobs:
 main:
    runs-on: ubuntu-latest
 

    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Container image
        run: docker build -t anupmenon22/tcs-mlf-spring-boot-docker .
      - name: Publish Docker image
        run: docker image push anupmenon22/tcs-mlf-spring-boot-docker
